version: '2'

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.61.0/24

volumes: 
  workspace: 
  
services:
  control:
    build: .
    image: dagman62/ubuntu-control
    container_name: control
    ports:
      - "2222:22"
    volumes:
      - ${PWD}/workspace:/root/workspace
    networks:
      custom:
        ipv4_address: 192.168.61.10
    dns: 8.8.8.8
    domainname: example.com 
    hostname: control
    extra_hosts:
      - "gitlab.example.com:192.168.1.116"
    restart: always
  node1:
    image: dagman62/ubuntu:sshd 
    container_name: node1
    ports:
       - "81:80"
    networks:
      custom:
        ipv4_address: 192.168.61.12
    dns: 8.8.8.8
    domainname: example.com
    hostname: node1
    restart: always
  node2:
    image: dagman62/ubuntu:sshd 
    container_name: node2
    ports:
       - "82:80"
    networks:
      custom:
        ipv4_address: 192.168.61.13
    dns: 8.8.8.8
    domainname: example.com
    hostname: node2
    restart: always
  lb:
    image: dagman62/ubuntu:sshd 
    container_name: lb
    ports:
      - "80:80"
    networks:
      custom:
        ipv4_address: 192.168.61.11
    dns: 8.8.8.8
    domainname: example.com
    hostname: lb
    restart: always

